# builder image
FROM golang:1.21-alpine as builder
RUN mkdir /build
ADD . /build/
WORKDIR /build
RUN go mod tidy
RUN go build -a -o reporting ./cmd/reporting/main.go


# final image
FROM alpine:3.19
COPY --from=builder /build/reporting .

# executable
ENTRYPOINT [ "./reporting" ]