version: '3'
services:
  tracking-api:
    image: tracking
    build:
      context: .
      dockerfile: ./Dockerfile.Tracking
    ports:
      - 9099:9099
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: stream
      AUTH_PASSWORD: 
      SECRET_KEY: 
      TOKEN_LIFESPAN: 1
  
  reporting:
    image: reporting
    build:
      context: .
      dockerfile: ./Dockerfile.Reporting
    depends_on:
      - mongo
    environment:
      MONGODB_HOST: mongo:27017
      MONGODB_DB: streams
      MONGODB_COLLECTION: users
      MONGODB_USER: 
      MONGODB_PASSWORD: 
      AUTH_PASSWORD: 
      SECRET_KEY: 
      TOKEN_LIFESPAN: 1
    ports:
      - 9098:9098
  
  consumer:
    image: consumer
    build:
      context: .
      dockerfile: ./Dockerfile.Consumer
    depends_on:
      - kafka
      - mongo
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: stream
      KAFKA_CONSUMER_GROUP: stream
      KAFKA_CONSUMER_STRATEGY: range
      MONGODB_HOST: mongo:27017
      MONGODB_DB: streams
      MONGODB_COLLECTION: users
      MONGODB_USER: 
      MONGODB_PASSWORD: 
  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 
      ME_CONFIG_MONGODB_ADMINPASSWORD: 
      ME_CONFIG_MONGODB_URL: 

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
