CREATE TABLE "streams" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" varchar NOT NULL,
  "device" varchar NOT NULL,
  "content" varchar NOT NULL,
  "geo" varchar NOT NULL,
  "started_at" timestamptz DEFAULT (now()),
  "fineshed_at" timestamptz DEFAULT NULL
);